### ISSUE TITLE
An error with virsorter2 of MetaPhage v2 beta

### ISSUE THREAD

**Issue by ilnamkang** [MattiaPandolfoVR/MetaPhage#57]
Hi,

I'm trying to use MetaPhage v2 beta.

When I tried running the program with the demo data, virsorter2 seemed to be throwing an error.
Below is the excerpt of the nextflow log.

\-----
Mar-01 23:32:44.967 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'virsorter2 (megahit-SRR8653090)'

Caused by:
  Process `virsorter2 (megahit-SRR8653090)` terminated with an error exit status (1)

Command executed:

  \# run virsorter2
  virsorter run     -j 8     -d /home/kangin/Programs/MetaPhage/db/virsorter/virsorter2/     --min-length 0     -i SRR8653090_megahit_contigs.fasta     --include-groups dsDNAphage,ssDNA     -w SRR8653090_virsorter2     -l SRR8653090     --rm-tmpdir
  \# add miner flag at each fasta header
  sed 's/^>/>virsorter2_/' SRR8653090_virsorter2/SRR8653090-final-viral-combined.fa > SRR8653090_virsorter2/SRR8653090-tmp-final-viral-combined.fa
  sed 's/||/ /' SRR8653090_virsorter2/SRR8653090-tmp-final-viral-combined.fa > SRR8653090_virsorter2/SRR8653090-correct-final-viral-combined.fa
  rm SRR8653090_virsorter2/SRR8653090-tmp-final-viral-combined.fa

Command exit status:
  1

Command output:
  (empty)

Command error:
  	2	merge_hmm_gff_features_by_group
  	2	merge_provirus_call_by_group_by_split
  	1	merge_provirus_call_from_groups
  	5	merge_split_hmmtbl
  	10	merge_split_hmmtbl_by_group
  	10	merge_split_hmmtbl_by_group_tmp
  	1	pick_viral_fullseq
  	1	preprocess
  	1	split_faa
  	2	split_faa_by_group
  	2	split_gff_by_group
  	61
  [2023-03-01 18:05 INFO] # of seqs < 0 bp and removed: 0
  [2023-03-01 18:05 INFO] # of circular seqs: 34
  [2023-03-01 18:05 INFO] # of linear seqs  : 13545
  [2023-03-01 18:05 INFO] Finish spliting circular contig file with common rbs
  [2023-03-01 18:05 INFO] Finish spliting linear contig file with common rbs
  [2023-03-01 18:12 INFO] Step 1 - preprocess finished.
  [2023-03-01 23:32 INFO] Step 2 - extract-feature finished.
  [2023-03-01 23:32 ERROR] See error details in SRR8653090_virsorter2/log/iter-0/step3-classify/all-score-ssDNA.log
  [Wed Mar  1 23:32:44 2023]
  Error in rule classify_by_group:
      jobid: 57
      output: iter-0/ssDNA/all.pdg.clf
      conda-env: /home/kangin/Programs/MetaPhage/db/virsorter/virsorter2/conda_envs/ca248a1a
      shell:
          
          Log=SRR8653090_virsorter2/log/iter-0/step3-classify/all-score-ssDNA.log
          python /home/kangin/miniconda3/envs/metaphage2/lib/python3.7/site-packages/virsorter/./scripts/classify.py iter-0/ssDNA/all.pdg.ftr /home/kangin/Programs/MetaPhage/db/virsorter/virsorter2/group/ssDNA/model ssDNA iter-0/ssDNA/all.pdg.clf 2> $Log || { echo "See error details in $Log" | python /home/kangin/miniconda3/envs/metaphage2/lib/python3.7/site-packages/virsorter/./scripts/echo.py --level error; exit 1; }
          
          (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
  
  [2023-03-01 23:32 ERROR] See error details in SRR8653090_virsorter2/log/iter-0/step3-classify/all-score-dsDNAphage.log
  [Wed Mar  1 23:32:44 2023]
  Error in rule classify_by_group:
      jobid: 56
      output: iter-0/dsDNAphage/all.pdg.clf
      conda-env: /home/kangin/Programs/MetaPhage/db/virsorter/virsorter2/conda_envs/ca248a1a
      shell:
          
          Log=SRR8653090_virsorter2/log/iter-0/step3-classify/all-score-dsDNAphage.log
          python /home/kangin/miniconda3/envs/metaphage2/lib/python3.7/site-packages/virsorter/./scripts/classify.py iter-0/dsDNAphage/all.pdg.ftr /home/kangin/Programs/MetaPhage/db/virsorter/virsorter2/group/dsDNAphage/model dsDNAphage iter-0/dsDNAphage/all.pdg.clf 2> $Log || { echo "See error details in $Log" | python /home/kangin/miniconda3/envs/metaphage2/lib/python3.7/site-packages/virsorter/./scripts/echo.py --level error; exit 1; }
          
          (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
  
  Exiting because a job execution failed. Look above for error message
  
  
  *** An error occurred. Detailed errors may not be printed for certain rules. Refer to the log file of the failed command for troubleshooting
  Issues can be raised at: https://github.com/jiarong/VirSorter2/issues

Work dir:
  /home/kangin/Programs/MetaPhage/work/ee/927252a8fccb827839641922502588`

\-----

I checked the two log files indicated by the error message: 
SRR8653090_virsorter2/log/iter-0/step3-classify/all-score-ssDNA.log
SRR8653090_virsorter2/log/iter-0/step3-classify/all-score-dsDNAphage.log

The last part of the two log files seem to indicate the same error.

\-----
  File "/home/kangin/Programs/MetaPhage/db/virsorter/virsorter2/conda_envs/ca248a1a/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
\-----

Is there any way to avoid this error?

Thanks.

**Comment by MattiaPandolfoVR** [comment]
Hi @ilnamkang,
thank you for bringing that to my attention, i'll look into it asap

**Comment by MattiaPandolfoVR** [comment]
Hi there @ilnamkang,
i was able to replicate this error and fix it.
It was related to an error of virsorter version 2.2.3, which was fixed in the recent release (2.2.4).

In order to fix this problem, i did the following:
1. I removed the virsorter2 db folder
`rm -rf "$METAPHAGE_DIR"/db/virsorter/virsorter2`
2. within the metaphage environment, i removed virsorter 2.2.3
`conda remove virsorter`
3. re-installed virsorter 2 (check that the version that will be installed is the 2.2.4 prior to confirm the installation)
`mamba install -c conda-forge -c bioconda virsorter=2`
4. re-run the virsorter2 download and setup
`virsorter setup --db-dir "$METAPHAGE_DIR"/db/virsorter/virsorter2 --jobs 4`
5. Re-launch the nextflow run command to launch metaphage, using the -resume option
nextflow run main.nf -profile local,debug_test -resume

I will update the .yaml file to avoid this error for other users, thank you

**Comment by ilnamkang** [comment]
Hi,

I followed your procedures, and virsorter2 ran successfully without errors.

Thank you for your help.

**Comment by hdflorezr** [comment]
> Hi there @ilnamkang, i was able to replicate this error and fix it. It was related to an error of virsorter version 2.2.3, which was fixed in the recent release (2.2.4).
> 
> In order to fix this problem, i did the following:
> 
> 1. I removed the virsorter2 db folder
>    `rm -rf "$METAPHAGE_DIR"/db/virsorter/virsorter2`
> 2. within the metaphage environment, i removed virsorter 2.2.3
>    `conda remove virsorter`
> 3. re-installed virsorter 2 (check that the version that will be installed is the 2.2.4 prior to confirm the installation)
>    `mamba install -c conda-forge -c bioconda virsorter=2`
> 4. re-run the virsorter2 download and setup
>    `virsorter setup --db-dir "$METAPHAGE_DIR"/db/virsorter/virsorter2 --jobs 4`
> 5. Re-launch the nextflow run command to launch metaphage, using the -resume option
>    `nextflow run main.nf -profile local,debug_test -resume`
> 
> I will update the .yaml file to avoid this error for other users, thank you

Hi, Mattia.

I follow all the steps but in the final step I received a report:

N E X T F L O W  ~  version 21.04.0
Launching `main.nf` [determined_pike] - revision: e1c3dcb0ab
Unknown configuration profile: 'local'

So, I re-launched the pipeline with the command:

nextflow run main.nf -c demo.conf --skip_metaquast -resume

In that case, It still shows the same last error.

I appreciate your help. Thank you.
